// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:7b6d5d33-6048-47a9-b116-745edfc46108",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_6k6em5zLJ",
    "aws_user_pools_web_client_id": "8kdd839evt2lkaag3a9u8i27t",
    "aws_appsync_graphqlEndpoint": "https://vccj4wen2nhjje7ed7pwgn5zs4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "pinme-pin-media",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
