// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:7b6d5d33-6048-47a9-b116-745edfc46108",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_6k6em5zLJ",
    "aws_user_pools_web_client_id": "8kdd839evt2lkaag3a9u8i27t"
};


export default awsmobile;
